### ISSUE TITLE
Commit "Add sphinx autodocumentation and remove ez_main" broke the pipe.

### ISSUE THREAD

**Issue by JNicL** [gsec/eZchat#18]
@bijancn your commit (d66640850a40379e43f056e1b52c14aa953cceae) broke the pipe as you were trying to start the client via a function. I see what you were trying to do and I tried to fix the bug, however, I did not succeed and I restored client.py and ez_cli.py to the previous state. 
With my latest commit print statments now get viewed in the statusline and you can see that the pipe between ez_cli and ez_p2p is working well.

**Comment by JNicL** [comment]
Solved. Starting a subprocess is not needed in our case. Init_client() in ez_client has to be called before ez_cli init.

**Comment by bijancn** [comment]
Sorry somehow this issue fell below my radar. The problem was that it prevented the automatic documentation. It is failing at the moment but I'm not sured if this is caused by ez_client.py

I also noticed that the documentation isn't automatically rebuild. @gsec could you do the following?

Github
If your project is hosted on Github, you can easily add a hook that will rebuild your docs whenever you push updates:

Go to the “Settings” page for your project
Click “Webhooks & Services”
In the “Services” section, click “Add service”
In the list of available services, click “ReadTheDocs”
Check “Active”
Click “Add service”
