### ISSUE TITLE
Messages have same UID

### ISSUE THREAD

**Issue by JNicL** [gsec/eZchat#21]
All messages sent have the same UID. I put the UID in the statusline so that you can verify.

**Comment by bijancn** [comment]
I wanted to start fixing issues when I noticed that @gsec and @JNicL broke literally every test. Looking at the build history, it starts with 8540265388cadcc790390249b49dc57a67ab7275.
1. The question 'Should /home/bijancn/eZchat/local/history be created? [y/n]' cannot be answered by nosetests. Dirty Fix in 33915c5. I guess we can just drop this asking completely. 
2. There is an indentation error in ez_crypto. Fixed in 33915c5.
3. local/keys/ez_rsa_Alice.priv and friends should be created automatically. At the moment, they are part of the repo. Not fixed yet.
4. ez_crypto is still failing

```
  File "/home/bijancn/eZchat/ez_crypto.py", line 266, in decrypt
    _key            = self.key.decode('base64')
AttributeError: 'NoneType' object has no attribute 'decode'
```

This propagates through into test_message and I would expect to cause this issue that all have the same UID. It's a miracle that you don't see crashes all the time.

Continuous integration and unit tests are useful as shit when you choose to ignore them.

**Comment by bijancn** [comment]
OK my bad. ez_crypto is not failing it was due to some old files lying around in my directory. How helpful it is look at Travis :P. So remaining issues are automatic creation of those private keys and wether this all messages have the same UID is still occuring. When I try python ez_cli.py, I get

```
Traceback (most recent call last):
  File "ez_cli.py", line 800, in <module>
    cl.init_client()
  File "/home/bijancn/test-ez/eZchat/ez_client.py", line 173, in init_client
    cl = client(name = sys.argv[1], write_to_pipe = True)
IndexError: list index out of range
```

EDIT: I remember: you want the username as first argument. Can we agree that it should take the user set in ez_preferences if not supplied with an argument?

**Comment by JNicL** [comment]
I found the bug. In ez_message: dtime is passed as an optional argument where the initial value is set to
dtime=datetime.now(), however, the value will stay the same for different instances and, thus, all messages have the same UID. This fixes at least the sync problem and I hope all other problems are fixed too. A push will follow in a minute.

**Comment by JNicL** [comment]
I ran some tests and everything seems awesome. It is now possible to send messages even if the user ain't online. Messages can then be retrieved via sync. An automated sync system will follow these days.
